
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProcess() : Promise<ProcessInfo[]> {
    return await TAURI_INVOKE("list_process");
},
async maxRunningProcess() : Promise<ProcessInfo | null> {
    return await TAURI_INVOKE("max_running_process");
},
async maxMemory() : Promise<ProcessInfo | null> {
    return await TAURI_INVOKE("max_memory");
},
async killProcess(id: string) : Promise<boolean> {
    return await TAURI_INVOKE("kill_process", { id });
},
async getFocusedApplication() : Promise<string | null> {
    return await TAURI_INVOKE("get_focused_application");
},
async blockWebsites(domains: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("block_websites", { domains }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unblockWebsite(domain: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unblock_website", { domain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlockedWebsites() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blocked_websites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActivityEntries() : Promise<Result<ActivityEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodayStats() : Promise<Result<DailyStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_today_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearTrackingData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_tracking_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSettingsWindow() : Promise<void> {
    await TAURI_INVOKE("show_settings_window");
},
async isExitBlocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_exit_blocked");
},
async setExitBlocked(block: boolean) : Promise<void> {
    await TAURI_INVOKE("set_exit_blocked", { block });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActivityEntry = { application: string; bundle_id: string | null; window_title: string | null; url: string | null; start_time: number; end_time: number; duration_seconds: number }
export type ActivitySummary = { application: string; bundle_id: string | null; total_duration_seconds: number; percentage: number }
export type DailyStats = { date: string; total_time_seconds: number; activities: ActivitySummary[]; websites: WebsiteSummary[] }
export type ProcessInfo = { id: string; nume: string; running_time_formatted: string; memory_in_bytes: number }
export type WebsiteSummary = { domain: string; total_duration_seconds: number; percentage: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
